menu/urls.py
from django.urls import path
from django.conf.urls.static import static
from spacetech import settings
from . import views
from django.urls import path
from .views import CustomPasswordResetConfirmView, actualizar_stock,  add_to_cart, checkout, crear_producto, crear_proveedor, decrement_quantity, descargar_pdf2, editar_proveedor, editar_publicidad, eliminar_proveedor, eliminar_publicidad, eliminar_solicitud_view,  enviar_publicidad, formulario_img, increment_quantity, inventario, listar_publicidades, publicar_solicitud_view,   remove_from_cart, remover_de_home, solicitud_publicidad_view, subir_a_home, transbank_response_publicidad,  ver_productos_proveedor, ver_solicitudes_view, view_cart
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import path
from .views import  iniciar_pago, confirmar_pago


urlpatterns = [
    path('', views.home_view, name='home'),
    path('menu', views.menu, name='menu'),

    path('busqueda_productos/', views.busqueda_productos),
    path('buscar/', views.buscar),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('agregarP', views.agregar_producto, name='agregarP'),
    path('update-profile/', views.update_profile_view, name='update_profile'),

    path('formulario', views.formulario, name='formulario'),
    path('listaU', views.listaU, name='listaU'),
    path('listaP', views.listaP, name='listaP'),
    

    path('listaU/eliminar/<int:usuario_id>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('listaU/editar/<int:usuario_id>/', views.editar_usuario, name='editar_usuario'),
    path('listaP/eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    path('listaP/modificar/<int:producto_id>/', views.modificarP, name='modificarP'),
    
    
    
    
  



    path('agregar_al_carrito/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('eliminar_del_carrito/<int:item_id>/', views.eliminar_del_carrito, name='eliminar_del_carrito'),
    path('incrementar_cantidad/<int:item_id>/', views.incrementar_cantidad, name='incrementar_cantidad'),
    path('decrementar_cantidad/<int:item_id>/', views.decrementar_cantidad, name='decrementar_cantidad'),
    path('carrito/', views.ver_carrito, name='ver_carrito'),

    path('comprar/', views.comprar, name='comprar'),

    path('venta_productos/', views.venta_productos, name='venta_productos'),
    path('guardar_direccion/', views.guardar_direccion, name='guardar_direccion'),



    path('webpay/iniciar/', views.iniciar_pago, name='iniciar_pago'),
    path('webpay/retorno/', views.retorno_pago, name='retorno_pago'),

    path('iniciar_pago/', iniciar_pago, name='iniciar_pago'),
    path('confirmar_pago/', confirmar_pago, name='confirmar_pago'),
    path('pago_exitoso/', views.pago_exitoso, name='pago_exitoso'),

    path('generar_pdf/', views.generar_pdf, name='generar_pdf'),
    path('enviar_pdf/', views.enviar_pdf, name='enviar_pdf'),

    path('gestion_ventas/', views.gestion_ventas, name='gestion_ventas'),
    path('detalle_venta_ajax/<int:venta_id>/', views.detalle_venta_ajax, name='detalle_venta_ajax'),    
    
    


   
    path('crear_proveedor/', views.crear_proveedor, name='crear_proveedor'),
    path('listar_proveedores/', views.listar_proveedores, name='listar_proveedores'),
    
   
    path('proveedor/eliminar/<int:id>/', eliminar_proveedor, name='eliminar_proveedor'),
    path('proveedor/editar/<int:id>/', editar_proveedor, name='editar_proveedor'),
    path('proveedor/<int:proveedor_id>/nuevo-producto/', crear_producto, name='crear_producto'),
    path('proveedor/<int:proveedor_id>/productos/', ver_productos_proveedor, name='ver_productos_proveedor'),
    
    path('producto/<int:producto_id>/añadir-al-carrito/', views.añadir_al_carrito, name='añadir_al_carrito'),   
    path('proveedor/<int:proveedor_id>/actualizar_carrito/', views.actualizar_carrito, name='actualizar_carrito'),

    path('proveedor/<int:proveedor_id>/crear_compra/', views.crear_compra, name='crear_compra'),
    path('compra/recepcion/', views.recepcion_compra, name='recepcion_compra'),
    path('compra/eliminar/<uuid:compra_id>/', views.eliminar_compra, name='eliminar_compra'),

    path('compra/<uuid:compra_id>/descargar_pdf2/', descargar_pdf2, name='descargar_pdf2'),

   
    path('inventario/', views.inventario, name='inventario'),
     path('subir_a_home/<int:producto_id>/', subir_a_home, name='subir_a_home'),
     path('remover_de_home/<int:producto_id>/', remover_de_home, name='remover_de_home'),
    path('producto/<int:id_producto>/', views.detalle_producto_view, name='detalle_producto'),




    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:item_id>/', remove_from_cart, name='remove_from_cart'),
    path('increment_quantity/<int:item_id>/', increment_quantity, name='increment_quantity'),
    path('decrement_quantity/<int:item_id>/', decrement_quantity, name='decrement_quantity'),
    path('cart/', view_cart, name='view_cart'),
    path('checkout/', checkout, name='checkout'),
    
    path('transbank_response/', views.transbank_response, name='transbank_response'),
    path('purchase_success/', views.purchase_success, name='purchase_success'),
    path('cambiar_estado_venta/', views.cambiar_estado_venta, name='cambiar_estado_venta'),

    path('formulario_img/', formulario_img, name='formulario_img'),
    
    

    path('publicidades/', listar_publicidades, name='listar_publicidades'),
    path('publicidades/editar/<int:publicidad_id>/', editar_publicidad, name='editar_publicidad'),
    path('publicidades/eliminar/<int:publicidad_id>/', eliminar_publicidad, name='eliminar_publicidad'),

    path('solicitud_publicidad/', solicitud_publicidad_view, name='solicitud_publicidad'),
    path('ver_solicitudes/', ver_solicitudes_view, name='ver_solicitudes'),
    path('eliminar_solicitud/<int:id>/', eliminar_solicitud_view, name='eliminar_solicitud'),

    path('solicitud_publicidad/', solicitud_publicidad_view, name='solicitud_publicidad'),
    path('transbank_response_publicidad/', transbank_response_publicidad, name='transbank_response_publicidad'),
    path('publicar_solicitud/<int:id>/', publicar_solicitud_view, name='publicar_solicitud'),

   
   path('actualizar_stock/<uuid:compra_id>/', views.actualizar_stock, name='actualizar_stock'),



     
]



# Clave de google maps api
# <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAUjMYm_HVdhncKSb4nvc8e4Br3-pbfbfc&callback=initMap&libraries=places" async defer></script>
# AIzaSyAUjMYm_HVdhncKSb4nvc8e4Br3-pbfbfc
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spacetech/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
    
    
]

menu/models.py
from datetime import timedelta
import uuid
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.models import Group


# Create your models here.


from django.db import models

class Usuario(models.Model):
    ROLE_CHOICES = [
        ('ADMIN', 'Administrador'),
        ('BODEGA', 'Bodeguero'),
        ('CLIENT', 'Cliente'),
    ]
    
    nombre_usuario = models.CharField(max_length=30)
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    email = models.EmailField(unique=True)
    tfno = models.CharField(max_length=8, verbose_name="Telefono")
    clave = models.CharField(max_length=30)
    confirmar_clave = models.CharField(max_length=30)
    direccion = models.CharField(max_length=255, verbose_name="Dirección", null=True, blank=True)
    role = models.CharField(max_length=6, choices=ROLE_CHOICES)
    
    def __str__(self):
        return f'{self.nombre} {self.apellido}'


    

class Articulos(models.Model):
    
    nombre = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=50)
    precio = models.IntegerField()
    stock = models.IntegerField()
    foto = models.ImageField(upload_to='static/img/', blank=True, null=True)
    marca = models.CharField(max_length=30, default='Sin Marca')
    precio_oferta = models.IntegerField(blank=True, null=True)
    descuento = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    

    def __str__(self):
        return self.nombre

class Pedidos(models.Model):
        numero=models.IntegerField()
        fecha=models.DateField()
        entregado=models.BooleanField()


class Carrito(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    creado_en = models.DateTimeField(auto_now_add=True)

class CarritoItem(models.Model):
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    producto = models.ForeignKey(Articulos, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=1)
    agregado_en = models.DateTimeField(default=timezone.now)        
    




class Comuna(models.Model):
    nombre = models.CharField(max_length=100)
    precio_envio = models.IntegerField(default=1)  # Precio de envío en pesos chilenos

    def __str__(self):
        return self.nombre



class Imagen(models.Model):
    
    imagen = models.ImageField(upload_to='static/img/')

    def __str__(self):
        return f"Imagen de {self.articulo.nombre}"
    

class Proveedor(models.Model):
    id_proveedor = models.AutoField(primary_key=True, editable=False)
    rut_empresa = models.CharField(max_length=13, verbose_name='RUT de la Empresa')
    nombre_empresa = models.CharField(max_length=100, verbose_name='Nombre de la Empresa')
    representante_legal = models.CharField(max_length=100, verbose_name='Representante Legal', default="")
    contacto_empresa = models.CharField(max_length=50, verbose_name='Contacto de la Empresa')
    direccion_proveedor = models.CharField(max_length=255, verbose_name='Dirección', default="sin direccion")
    email_proveedor = models.EmailField(max_length=70, unique=True, null=True, blank=True)

    def str(self):
        return self.nombre_empresa



    



class Producto(models.Model):
    id_producto = models.AutoField(primary_key=True, editable=False)
    nombre_producto = models.CharField(max_length=100, verbose_name='Nombre del Producto')
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE, verbose_name='Proveedor')
    stock_actual = models.IntegerField(verbose_name='Stock Actual', null=True, blank=True)
    stock_minimo = models.IntegerField(verbose_name='Stock Mínimo', null=True, blank=True)
    precio_costo = models.IntegerField(verbose_name='Precio de Costo')
    precio_venta = models.IntegerField(verbose_name='Precio de Venta', default=0)
    foto_producto = models.ImageField(upload_to='static/img/', verbose_name='Foto del Producto', null=True, blank=True)
    mostrar_en_home = models.BooleanField(default=False, verbose_name='Mostrar en Home')    
    
    def __str__(self):
        return self.nombre_producto


class Compra(models.Model):
    id_orden_compra = models.UUIDField(primary_key=True, editable=False)
    fecha = models.DateTimeField(auto_now_add=True)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE, verbose_name='Proveedor')
    sub_total = models.IntegerField()
    iva = models.IntegerField()
    total = models.IntegerField()

    def __str__(self):
        return f'Compra {self.id_orden_compra} - {self.proveedor.nombre_empresa}'  


class DetalleCompra(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    orden_compra = models.ForeignKey(Compra, on_delete=models.CASCADE, verbose_name='Orden de Compra', related_name='detalles')
    correlativo = models.IntegerField(verbose_name='Número Correlativo')
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name='Producto')
    cantidad = models.IntegerField()
    precio_costo = models.IntegerField()
    sub_total = models.IntegerField()
    cantidad_llegada = models.IntegerField(default=0, verbose_name='Cantidad Llegada')

    def __str__(self):
        return f'Detalle {self.correlativo} de {self.orden_compra}'
    
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Producto, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    added_at = models.DateTimeField(default=timezone.now)

# models.py
class Venta(models.Model):
    ESTADO_CHOICES = [
        ('Pendiente', 'Pendiente'),
        ('Entregado', 'Entregado'),
    ]
    
    id = models.AutoField(primary_key=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    id_boleta = models.CharField(max_length=30)
    fecha = models.DateTimeField(default=timezone.now)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)
    iva = models.DecimalField(max_digits=10, decimal_places=2)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    direccion_retiro = models.CharField(max_length=255, default="Piedra Roja 125, Quilicura, Chile")  # Dirección de retiro
    estado = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='Pendiente')  # Estado de la venta

    def __str__(self):
        return f'Venta {self.id} - Usuario {self.usuario.nombre_usuario}'


class DetalleVenta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'Detalle de Venta {self.venta.id} - Producto {self.producto.nombre_producto}'    
    



from django.db import models

class Publicidad(models.Model):
    imagen = models.ImageField(upload_to='publicidad/')
    
    activa = models.BooleanField(default=True)
    duracion = models.IntegerField(default=5)  # Duración en segundos

    def __str__(self):
        return f'Publicidad {self.id}'
    


class SolicitudPublicidad(models.Model):
    imagen = models.ImageField(upload_to='publicidades/')
    tiempo = models.IntegerField(choices=[(1, '1 Semana'), (2, '2 Semanas'), (4, '1 Mes'), (12, '3 Meses')])
    segundos = models.IntegerField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    
    fecha_vencimiento = models.DateTimeField(null=True, blank=True)
    publicada = models.BooleanField(default=False)
    
    def __str__(self):
        return f"Publicidad - {self.get_tiempo_display()}, {self.segundos} segundos"

    def __str__(self):
        return f"Publicidad - {self.tiempo} semanas, {self.segundos} segundos"

menu/templates/agregarP.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Form</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Custom CSS -->
    <style>
        body {
            background-color: #f8f9fa;
            font-family: Arial, sans-serif;
        }
        .form-container {
            max-width: 900px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 10px;
            background-color: #fff;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        }
        .form-title {
            text-align: center;
            margin-bottom: 20px;
        }
        .form-label {
            font-weight: bold;
        }
        .btn-submit {
            display: block;
            width: 100%;
            padding: 10px;
            font-size: 18px;
        }
    </style>
</head>
<body>
    {% include "plantilla/menu.html" %}
    <div class="container mt-5">
        <div class="form-container">
            <h1 class="form-title">Agregar Producto</h1>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="nombre" class="form-label">Nombre:</label>
                        <input type="text" name="nombre" class="form-control" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="descripcion" class="form-label">Descripción:</label>
                        <input type="text" name="descripcion" class="form-control" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="precio" class="form-label">Precio:</label>
                        <input type="number" name="precio" class="form-control" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="stock" class="form-label">Stock:</label>
                        <input type="number" name="stock" class="form-control" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="marca" class="form-label">Marca:</label>
                        <input type="text" name="marca" class="form-control" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="precio_oferta" class="form-label">Precio de Oferta:</label>
                        <input type="number" name="precio_oferta" class="form-control">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="descuento" class="form-label">Descuento (%):</label>
                        <input type="number" step="0.01" name="descuento" class="form-control">
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="fotoProducto" class="form-label">Foto del Producto:</label>
                        <input type="file" class="form-control" name="foto" id="foto">
                    </div>
                </div>
                <h3>Imágenes del Producto</h3>
                <div class="row">
                    {{ formset.management_form }}
                    {% for form in formset %}
                        <div class="col-md-4 mb-3">
                            {{ form.as_p }}
                        </div>
                    {% endfor %}
                </div>
                <button type="submit" class="btn btn-primary btn-submit">Enviar</button>
            </form>
        </div>
    </div>

    <!-- Bootstrap JS (optional) -->
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
   
</body>
</html>

menu/templates/agregar_producto_proveedor.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Producto</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f8f9fa;
        }
        .container {
            margin-top: 50px;
        }
        .form-group {
            margin-bottom: 15px;
        }
        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
        }
        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #004085;
        }
        .card {
            border: none;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">Agregar Producto para {{ proveedor.nombre_empresa }}</h1>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">Guardar Producto</button>
                    <a href="{% url 'proveedor_list' %}" class="btn btn-secondary">Cancelar</a>
                </form>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

menu/templates/busqueda_productos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>Document</title>
</head>


<body>
    
    <form action="/buscar/" method="get">  

        <input type="text"  name="prd" >
        <input type="submit" value="Buscar">

    </form>






</body>
</html>

menu/templates/crear_producto.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Crear Producto</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>

        .container {
            background-color: #2a2a2a; /* Morado oscuro */
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.2);
        }
        h1 {
            color: #FFFFFF; /* Texto blanco */
        }
        .btn-primary {
            background-color: #8C52FF; /* Morado */
            border-color: #8C52FF; /* Borde del botón */
        }
        label {
            color: #FFFFFF; /* Texto blanco para etiquetas */
        }
    </style>
</head>
<body style="color: white;">
    {% include "plantilla/menu.html" %}

    <div class="container mt-4">
        <h1>Crear Nuevo Producto</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_nombre_producto" class="form-label">Nombre del Producto</label>
                <input type="text" class="form-control" id="id_nombre_producto" name="nombre_producto">
            </div>
            <div class="mb-3">
                <label for="id_precio_costo" class="form-label">Precio de Costo</label>
                <input type="number" class="form-control" id="id_precio_costo" name="precio_costo">
            </div>
            <div class="mb-3">
                <label for="id_foto_producto" class="form-label">Foto del Producto</label>
                <input type="file" class="form-control" id="id_foto_producto" name="foto_producto">
            </div>
            <button type="submit" class="btn btn-primary">Guardar Producto</button>
        </form>
    </div>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

menu/templates/crear_proveedor.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Crear Proveedor</title>
    <!-- Añadir CSS de Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Añadir CSS personalizado -->
    <style>
        .container {
            background-color: #262527;
            padding: 20px;
            border-radius: 8px;
        }
        .form-label {
            color: #f8f8f8;
        }
        .btn-primary {
            background-color: #8C52FF;
            border: none;
        }
        .btn-primary:hover {
            background-color: #6e3fcc;
        }
    </style>
</head>
<body style="background-color: rgb(222, 222, 222);">
    {% include "plantilla/menu.html" %} 
       <div class="container mt-5">
        <h1 class="mb-3" style="color: azure;">Crear Nuevo Proveedor</h1>
        <form method="post" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_rut_empresa" class="form-label">RUT de la Empresa</label>
                <input type="text" class="form-control" id="id_rut_empresa" name="rut_empresa" required>
                <div class="invalid-feedback">
                    Por favor, ingrese el RUT de la empresa.
                </div>
            </div>
            <div class="mb-3">
                <label for="id_nombre_empresa" class="form-label">Nombre de la Empresa</label>
                <input type="text" class="form-control" id="id_nombre_empresa" name="nombre_empresa" required>
                <div class="invalid-feedback">
                    Por favor, ingrese el nombre de la empresa.
                </div>
            </div>
            <div class="mb-3">
                <label for="id_representante_legal" class="form-label">Representante Legal</label>
                <input type="text" class="form-control" id="id_representante_legal" name="representante_legal" required>
                <div class="invalid-feedback">
                    Por favor, ingrese el nombre del representante legal.
                </div>
            </div>
            <div class="mb-3">
                <label for="id_contacto_empresa" class="form-label">Contacto de la Empresa</label>
                <input type="text" class="form-control" id="id_contacto_empresa" name="contacto_empresa" required>
                <div class="invalid-feedback">
                    Por favor, ingrese el contacto de la empresa.
                </div>
            </div>
            <div class="mb-3">
                <label for="id_direccion_proveedor" class="form-label">Dirección</label>
                <input type="text" class="form-control" id="id_direccion_proveedor" name="direccion_proveedor" required>
                <div class="invalid-feedback">
                    Por favor, ingrese la dirección del proveedor.
                </div>
            </div>
            <div class="mb-3">
                <label for="id_email_proveedor" class="form-label">Email</label>
                <input type="email" class="form-control" id="id_email_proveedor" name="email_proveedor">
                <div class="invalid-feedback">
                    Por favor, ingrese un email válido.
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Guardar Proveedor</button>
            <a href="{% url 'listar_proveedores' %}" class="btn btn-danger">Cancelar</a>

            
        </form>
    </div>
    <!-- Añadir JS de Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Script para validación de formularios -->
</body>
</html>

menu/templates/pago_fallido.html
<!-- templates/pago_fallido.html -->

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pago Fallido</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h2 class="mt-4">Pago Fallido</h2>
        <div class="card">
            <div class="card-body">
                <h3 class="section-title">Detalles del Error</h3>
                <p>Hubo un problema al procesar tu pago. Por favor, intenta nuevamente.</p>
                <p><strong>Mensaje:</strong> {{ response.error_message }}</p>
            </div>
        </div>
        <a href="{% url 'venta_productos' %}" class="btn btn-primary mt-4">Volver a la tienda</a>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>